### ISSUE TITLE
Removing A Version Does Not Remove Asset From The File System

### ISSUE THREAD

**Issue by rileyz** [omaha-consulting/winget.pro#11]
**Summary**
Checking the "delete" checkbox in the version area if a package and removing does not remove the asset from the file system.

**Version:**
VPS on Ubuntu minimal install (ubuntu-22.04.2-live-server-amd64.iso). 
Sorry I couldn't find the version of WinGetPro  from the web interface, but I installed on the Monday 5th Feb.

**Actions to reproduce:**
1. WinGetPro web interface, add package.
2. WinGetPro web interface, add version.
3. SSH session, ls /srv/media/tenantguid shows the package uploaded.
4. WinGetPro web interface, remove version, check/tick checkbox for "Delete". Procced by clicking "Remove" or "Save"
5. SSH session, ls /srv/media/tenantguid package asset should be removed.

**Expectation:** 
Version marked for deletion  with "Delete" should also remove the asset from the directory.

**Actual outcome:** 
Asset still located in directory.

**Side notes:**
I thought there could be a internal task, or cron job just that does the clean-up, but I have left it for a week and the old assets are still located in the /srv/media/tenantguid.  I noticed the removal of the assets issue in the VPS and local version, I only used the local version for a few days though.

**Comment by mherrmann** [comment]
Thank you for the nice report. Fixed in 59c71cd5e1a2fce4f30fe34a14a4a2b7b54f59a9.
