### ISSUE TITLE
Just a question for understanding 

### ISSUE THREAD

**Issue by JZafarr** [omaha-consulting/winget.pro#13]
Hi there, 

Could you please explain how these options work or point me towards any documentation that might be available. Or are they just for the reference to remember the flags.
![Screenshot 2024-02-20 001814](https://github.com/omaha-consulting/winget.pro/assets/62207359/9199d1ef-0e48-4e81-ba88-48129807297c)

Is there an option to force install or silent install for the packages available on the internet or are they always going to be interactive installations. Just wanted to clarify that. I've tried using the silent switch in winget from my private repo but the free software i was using was downloaded from the internet and it always comes up with an interactive installation prompt.

**Comment by mherrmann** [comment]
We just uploaded a new version that tries to improve those help texts:

![image](https://github.com/omaha-consulting/winget.pro/assets/1076393/79c9f108-79f8-450d-961e-ca22533873ad)

The "Silent progress switch" is the default when you type `winget install`. If you upload an installer from the internet to your private winget.Pro repository, then you need to find out what the silent switch is for it. Alternatively, you can find out how the installer was generated, and select this type in the "Type" dropdown:

![image](https://github.com/omaha-consulting/winget.pro/assets/1076393/ec8ea819-dcfc-4c7b-a18b-e0c9d9ae7e4a)

For example, if the installer was created with NSIS ("Nullsoft Install System") and you select "nullsoft" in the type dropdown, then the correct silent switches should automatically be added.

**Comment by JZafarr** [comment]
okay it works, i just tried msi installer instead of exe and it appears to work now. thanks for clarifying.

**Comment by JZafarr** [comment]
okay it works, i just tried msi installer instead of exe and it appears to work now. thanks for clarifying.

**Comment by mherrmann** [comment]
Hi @spookyfox, it always depends on the installer. I recommend looking up the command line options for the installer you upoladed.
