### ISSUE TITLE
Failure at Docker Compose Up - Cannot find Dockerfile

### ISSUE THREAD

**Issue by excelsi** [omaha-consulting/winget.pro#15]
I get following error when i try to spinup the Container:

```
root@SRV-CON1:/home/wingetpro# docker compose up
[+] Building 0.1s (2/2) FINISHED                                                                         docker:default
 => [django internal] load build definition from Dockerfile                                                        0.1s
 => => transferring dockerfile: 2B                                                                                 0.0s
 => [django internal] load .dockerignore                                                                           0.1s
 => => transferring context: 2B                                                                                    0.0s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount369694079/Dockerfile: no such file or directory
```

I have all the files in my wingetpro directory. I also tried to create the directory /var/lib/docker/tmp/buildkit-mount369694079 and moved the Dockerfile there but still the same error.
I also tried the tips here:
https://github.com/docker/for-win/issues/8781

But all this didn't help.
I was able to spinup other containers on this host with docker compose and dockerfile in the same directory already. 

Can you provide me some help/guidance here?
Thanks for your help!

**Comment by mherrmann** [comment]
Shouldn't the command be `docker-compose up`?

**Comment by excelsi** [comment]
Already tried that and had the same problem with my other container spinups before:
```
root@SRV-CON1:/home/wingetpro# docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```
It seems that it cannot handle the Version here.

**Comment by mherrmann** [comment]
Have you tried installing compatible versions of docker and docker-compose?

**Comment by excelsi** [comment]
how can i find the current versions and how can i force to install compatible versions?
thanks!

**Comment by mherrmann** [comment]
Please use our hosted option on https://winget.pro/start. Then you don't have to deal with such problems.

**Comment by excelsi** [comment]
No problem i love to deal with deal with it, im a container newbie ;-)
I will try further by myself but thanks for you response!

**Comment by mherrmann** [comment]
Alright. Then I'll close this for now.
