### ISSUE TITLE
Feature: Add overrideable cookie settings

### ISSUE THREAD

**Issue by randywatson1979** [omaha-consulting/winget.pro#19]
Hi guys, thanks for all the great work!

May I suggest adding cookie settings in settings.py? The default session cookie expires after two weeks, but for security it might be better when we reduce that and only extended after each request within the expiry period?

`SESSION_COOKIE_AGE = 180 # 3 minutes`
`SESSION_SAVE_EVERY_REQUEST = True # "False" by default`

Perhaps this is configurable via enviroment variable?

**Comment by mherrmann** [comment]
Hi, as this is a feature related to security, we can implement it for you if you subscribe to one of our paid options at https://winget.pro/start/. If you wish to self-host, select the _Enterprise_ option.
