### ISSUE TITLE
Please log in at /admin for instructions.

### ISSUE THREAD

**Issue by emircankavas** [omaha-consulting/winget.pro#5]
When I send GET request to repository URL, it says:
`Please log in at /admin for instructions.`

It gives information about application and it might be a security vulnerability. Can we disable this response?

**Comment by mherrmann** [comment]
Fair point. This is fixed now in the [private version of winget.Pro with security fixes](https://buy.stripe.com/cN24k9crz91re8U9AO). The fix will appear in this public repository in 6 months.
