### ISSUE TITLE
Wrong download URL (deployed with described test SSL Proxy)

### ISSUE THREAD

**Issue by mitreutera** [omaha-consulting/winget.pro#6]
I deployed the project with docker desktop as described (with the SSL Proxy for testing purpose).

**Two small suggestions first:**
I was able to add the source via the URL written on the Home/Welcome page, however only after adding the port of the SSL proxy. Can that be changed? Might have to do with my actual problem...

~~I also had to edit the nginx.config by adding "client_max_body_size 500M" so it would allow me to upload my file for testing (gimp, around 300 MB). Am I right to assume, that this change is kinda mandatory, as long as I'm uploading bigger files?~~ - already fixed

I hope it's ok to put these two (small) issues in here, since I expect them to be easy fixes.

**But now for my main problem:**
When running a script that basically runs "winget install --exact --silent Gimp.Gimp --source localhost --accept-package-agreements" It finds the package at the repository and tries to download it, but fails to do so, since the download URL doesn't contain the port. 
Where does winget.pro get the root URL it passes to winget from? Am I missing something, or does the download just not work in this SSL Proxy test environment?

I guess it's not a problem when you have a setup with a proper Proxy (HTTPS under the usual port 443), but right now the download URL it passes is http and without the needed port (8000 or probably 8443 so winget doesn't complain) so it fails with a 404.

**Comment by rileyz** [comment]
The "local" version is for development, hence the setup. If you want WinGetPro to work correctly over HTTPS then you need to implement the "VPS" version. I can confirm the winget install is called over HTTPS.  

If you want to keep using the "local" version of WinGetPro, you can use netsh to rediect port 80 to port 8000, where its listening. See URL below for clues.
https://stackoverflow.com/questions/11525703/port-forwarding-in-windows

Sorry I cant provide the exact command, I was using the "local" version but decided to implement the "VPS" version a week back. But the netsh redirect does work.

**Comment by mitreutera** [comment]
Oh ok. Thanks for the tips, I'll try that. Or maybe I'll go for a proper environment directly, I guess I'm already sold on the concept, no need to try around any further.

Thanks again :)
