### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by JZafarr** [omaha-consulting/winget.pro#7]
Hi there,

When I try to upload the installer - in this case Mozilla Firefox, I get this error 413 Request Entity Too Large

I have installed winget pro via docker.

**Comment by mitreutera** [comment]
You can edit the nginx.config under winget.pro/run/docker by adding "client_max_body_size 500M" in http like that:

![image](https://github.com/omaha-consulting/winget.pro/assets/156071435/66b4a9eb-b4d1-46ca-93ec-0d225a8f128d)

You can choose your own size (or go unlimited by entering 0). It's only a temporary workaround though, and you might have to rebuild your container (and maybe delete the volumes, i tried redoing things a few times, at some point it worked).

**Comment by mherrmann** [comment]
Thanks. This is fixed in the latest revision.

**Comment by JZafarr** [comment]
Thank you, it has worked, I had to bring down the container and bring it up again and its now working.
