### ISSUE TITLE
CSS Formatting broken 

### ISSUE THREAD

**Issue by JZafarr** [omaha-consulting/winget.pro#8]
I was testing the packages and installers, everything was working, I installed and uninstalled a few packages and now my formatting is broken.
Is there anyway I can fix it or do I have to reinstall?
Im running the winget.pro app via docker.
![Screenshot 2024-02-02 011208](https://github.com/omaha-consulting/winget.pro/assets/62207359/3551a523-33a8-4b48-acfa-a75a8d9a3166)

**Comment by JZafarr** [comment]
I have changed the directory location from /var/lib/docker to /opt folder and have given 755 permission to the directory. It was working perfectly fine until it was not.

**Comment by mherrmann** [comment]
Why do you need to change the directory location?

**Comment by JZafarr** [comment]
No particular reason, just wanted to keep all the data in one directory, but its not important, I have reinstalled it in default location and it appears to be working for now, you can close this issue.
